### PR TITLE
IntG with multiple kernels

### PR DESCRIPTION
**Pull request by isuruf**
- [x] Requires inducer/sumpy#23
- [x] Point `requirements.txt` back to master

### CODE REVIEW

File: pytential/qbx/interactions.py [hunk 1]
```diff
@@ -42,6 +42,8 @@ def get_cache_key(self):
 
     def get_kernel(self):
         ncoeffs = len(self.expansion)
+        print(self.source_kernels)
+        print(self.expansion)
```
Comment (inducer) [inline pytential/qbx/interactions.py:46]:
```suggestion
```

File: pytential/symbolic/compiler.py [hunk 2]
```diff
@@ -146,12 +146,12 @@ class ComputePotentialInstruction(Instruction):
 
         a dictionary mapping arg names to kernel arguments
 
-    .. attribute:: base_kernel
+    .. attribute:: source_kernels
 
-        The common base kernel among :attr:`kernels`, with all the
+        The common source kernels among :attr:`target_kernels`, with all the
         layer potentials removed.
```
Comment (inducer) [inline pytential/symbolic/compiler.py:152]: This docstring doesn't make sense.

File: pytential/symbolic/compiler.py [hunk 3]
```diff
@@ -146,12 +146,12 @@ class ComputePotentialInstruction(Instruction):
...
 
-    .. attribute:: density
+    .. attribute:: densities
```
Comment (inducer) [inline pytential/symbolic/compiler.py:154]: Document how "source kernels" are associated with densities.

File: pytential/symbolic/compiler.py [hunk 4]
```diff
@@ -198,9 +202,19 @@ def __str__(self):
             else:
                 raise ValueError(f"unrecognized limit value: {o.qbx_forced_limit}")
 
+            source_kernels_strs = [
+                f"density{i} * {source_kernel}" for i, source_kernel in
+                enumerate(self.source_kernels)
+            ]
+            source_kernels_str = " + ".join(source_kernels_strs)
```
Comment (inducer) [inline pytential/symbolic/compiler.py:209]: No need for the `source_kernels_strs` temporary.

File: pytential/symbolic/compiler.py [hunk 5]
```diff
@@ -569,20 +583,19 @@ def map_int_g(self, expr, name_hint=None):
...
-            kernel_to_index = {kernel: i for i, kernel in enumerate(kernels)}
-
+            sorted_ops = sorted(group, key=lambda op: repr(op.target_kernel))
+            target_kernels = [op.target_kernel for op in sorted_ops]
             from pytools import single_valued
-            from sumpy.kernel import AxisTargetDerivativeRemover
-            atdr = AxisTargetDerivativeRemover()
-            base_kernel = single_valued(
-                    atdr(kernel) for kernel in kernels)
+            source_kernels = single_valued(op.source_kernels for op in sorted_ops)
```
Comment (inducer) [inline pytential/symbolic/compiler.py:595]: Why are these expected to be `single_valued`?

File: pytential/symbolic/compiler.py [hunk 6]
```diff
@@ -569,20 +583,19 @@ def map_int_g(self, expr, name_hint=None):
...
+                density in expr.densities]
 
             group = self.group_to_operators[self.op_group_features(expr)]
             names = [self.get_var_name() for op in group]
 
-            kernels = sorted({op.kernel for op in group}, key=repr)
-
-            kernel_to_index = {kernel: i for i, kernel in enumerate(kernels)}
-
+            sorted_ops = sorted(group, key=lambda op: repr(op.target_kernel))
```
Comment (inducer) [inline pytential/symbolic/compiler.py:592]: Wouldn't you need similar sorting/normalization logic for "source kernels"?

File: pytential/symbolic/matrix.py [hunk 7]
```diff
@@ -557,40 +570,43 @@ def map_int_g(self, expr):
...
+            from meshmode.dof_array import flatten, thaw
+            _, (mat,) = mat_gen(actx.queue,
+                    targets=flatten(thaw(actx, target_discr.nodes())),
+                    sources=flatten(thaw(actx, source_discr.nodes())),
+                    index_set=self.index_set,
+                    **kernel_args)
+
+            result += rec_density * actx.to_numpy(mat)
+
+        return result
```
Comment (inducer) [inline pytential/symbolic/matrix.py:609]: @alexfikl Could you take a look at this? See https://github.com/inducer/sumpy/pull/23/files for context?

File: pytential/symbolic/stokes.py [hunk 8]
```diff
@@ -123,12 +123,12 @@ def apply(self, density_vec_sym, mu_sym, qbx_forced_limit):
                 ctr_key = tuple(var_ctr)
 
                 if i < 1:
-                    sym_expr[comp] = sym.IntG(
+                    sym_expr[comp] = sym.S(
```
Comment (inducer) [inline pytential/symbolic/stokes.py:126]: I find this notationally weird, given that these are not single layer potentials really. I think we should have an `IntG`-like thing that vectorizes over densities. (and not use `S`)

File: test/test_scalar_int_eq.py [hunk 9]
```diff
@@ -195,7 +195,7 @@ def run_int_eq_test(actx: PyOpenCLArrayContext,
 
     # {{{ establish BCs
 
-    pot_src = sym.IntG(
+    pot_src = sym.S(
```
Comment (inducer) [inline test/test_scalar_int_eq.py:198]: As with Stokes.

File: test/test_layer_pot.py [hunk 10]
```diff
@@ -267,7 +283,7 @@ def test_unregularized_with_ones_kernel(ctx_factory):
 
     from sumpy.kernel import one_kernel_2d
     sigma_sym = sym.var("sigma")
-    op = sym.IntG(one_kernel_2d, sigma_sym, qbx_forced_limit=None)
+    op = sym.S(one_kernel_2d, sigma_sym, qbx_forced_limit=None)
```
Comment (inducer) [inline test/test_layer_pot.py:286]: As with Stokes: `sym.S` is mathematically/notationally weird.

File: test/test_layer_pot.py [hunk 11]
```diff
@@ -231,6 +234,19 @@ def test_off_surface_eval_vs_direct(ctx_factory,  do_plot=False):
...
+        densities=op_d.densities + (sym.var("sigma")*0.5,))
+    single_fmm_bound_op = bind(places, op, auto_where=("fmm_qbx", "target"))
+    print(single_fmm_bound_op.code)
+    single_fmm_fld_in_vol = fmm_bound_op(actx, sigma=fmm_sigma)
+
+    err = actx.np.fabs(fmm_fld_in_vol - single_fmm_fld_in_vol)
+    linf_err = actx.to_numpy(err).max()
+    print("l_inf error:", linf_err)
+
+    assert linf_err < 1e-15
```
Comment (inducer) [inline test/test_layer_pot.py:248]: How come it's sensible to bolt this into an existing test case? (Rather than make it its own?)

File: pytential/symbolic/mappers.py [hunk 12]
```diff
@@ -515,8 +513,7 @@ def map_int_g(self, expr):
                 for name, arg_expr in expr.kernel_arguments.items()}
 
         return expr.copy(
-                kernel=expr.kernel,
```
Comment (inducer) [inline pytential/symbolic/mappers.py:518]: Any idea why this was here in the first place?

File: pytential/symbolic/mappers.py [hunk 13]
```diff
@@ -181,16 +181,12 @@ def map_num_reference_derivative(self, expr):
...
-                        expr.kernel,
-                        self.rec(subexpr),
-                        expr.qbx_forced_limit, expr.source, expr.target,
-                        kernel_arguments={
-                                name: self.rec(arg_expr)
-                                for name, arg_expr in expr.kernel_arguments.items()
-                                }),
-                expr.density)
+        return expr.copy(
+                    densities=[self.rec(density) for density in expr.densities],
```
Comment (inducer) [inline pytential/symbolic/mappers.py:185]: Wouldn't `self.rec` automatically walk the list?

File: pytential/symbolic/mappers.py [hunk 14]
```diff
@@ -670,14 +666,23 @@ def _stringify_kernel_args(self, kernel_arguments):
                     for name, arg_expr in kernel_arguments.items())
 
     def map_int_g(self, expr, enclosing_prec):
-        return "Int[{}->{}]@({}){} ({} * {})".format(
+        source_kernels_strs = [
+            "{} * {}".format(self.rec(density, PREC_PRODUCT), source_kernel)
+            for source_kernel, density in zip(expr.source_kernels, expr.densities)
+        ]
+        source_kernels_str = " + ".join(source_kernels_strs)
```
Comment (inducer) [inline pytential/symbolic/mappers.py:673]: No need for the `source_kernels_strs` temporary.

**Review by inducer — COMMENTED** [review]
Thanks for working on this. A few comments below.

File: pytential/symbolic/mappers.py (hunk 12 above)
Comment (alexfikl) [reply pytential/symbolic/mappers.py:518]: In this particular place, I think it's my fault, but I probably just copied it over from one of the other mappers.

File: pytential/symbolic/matrix.py (hunk 7 above)
Comment (alexfikl) [reply pytential/symbolic/matrix.py:609]: Looks good to me!

What's a source/target kernel? (Couldn't find any sufficiently dumbed-down docs :(

Comment (isuruf) [reply pytential/symbolic/matrix.py:609]: Thanks for having a look. Here's an explanation that I just added, https://github.com/inducer/pytential/blob/392afb3db03cf72991d5acd01d28f89e7e5cbb2c/pytential/symbolic/primitives.py#L1424
Let me if that is sufficient. If not, I can improve the docstring.

File: pytential/symbolic/compiler.py (hunk 6 above)
Comment (isuruf) [reply pytential/symbolic/compiler.py:596]: target kernels sorting was probably needed to get deterministic code after collecting IntGs. Since source_kernels is an attribute of the IntGs, they need not be sorted. We could sort them along with the densities with the same ordering, but I don't think it's necessary.

File: pytential/symbolic/matrix.py (hunk 7 above)
Comment (alexfikl) [reply pytential/symbolic/matrix.py:609]: That clears it up for me. Thanks!

File: pytential/symbolic/compiler.py (hunk 6 above)
Comment (inducer) [reply pytential/symbolic/compiler.py:596]: No, the sorting is there to standardize the operations. Otherwise, `S, dx S` and `dx S, S` would each generate their own code. IMO, a similar concern exists for source derivatives.

Btw, it might be useful to add a comment to the sort to explain its reason for existing.

Comment (isuruf) [reply pytential/symbolic/compiler.py:596]: Got it. Then there's no need to sort target kernels then. Only source kernels.

Comment (inducer) [reply pytential/symbolic/compiler.py:596]: Not sure I agree. We should talk through the implications of this tomorrow.

**Comment by isuruf** [comment]
This and the sumpy PR are ready

File: pytential/utils.py [hunk 15]
```diff
@@ -61,4 +61,8 @@ def flatten_to_numpy(actx, ary):
     from pytools.obj_array import obj_array_vectorize
     return obj_array_vectorize(actx.to_numpy, result)
 
+
+def sort_arrays_together(*arys):
+    return zip(*sorted([x for x in zip(*arys)]))
```
Comment (inducer) [inline pytential/utils.py]: Docstring?

File: pytential/source.py [hunk 16]
```diff
@@ -128,10 +128,16 @@ def ambient_dim(self):
...
+        # since IntGs with the same source kernels and densities calculations
+        # for P2E and E2E are the same and only differs in E2P depending on the
+        # target kernel, we group all IntGs with same source kernels and densities.
+        # sorting is done to avoid duplicates as the order of the sum of source
+        # kernels does not matter.
         result = (
-                expr.source, expr.densities, expr.source_kernels,
-                AxisTargetDerivativeRemover()(expr.target_kernel),
+                expr.source,
+                *sort_arrays_together(expr.densities, expr.source_kernels),
```
Comment (inducer) [inline pytential/source.py]: I'm honestly surprised this succeeds---pymbolic expressions are [unordered](https://github.com/inducer/pymbolic/blob/ca9dcc5befe13b7a29fdfbc21ec687a23398b2ec/pymbolic/primitives.py#L633-L643)? What is it sorting by? [For the target derivatives](https://github.com/inducer/pytential/blob/b6e627ef815c740324e553615b2f4e21292b39ae/pytential/symbolic/compiler.py#L577), I ended up using `repr` as the sort key.

File: pytential/symbolic/compiler.py [hunk 17]
```diff
@@ -585,20 +585,19 @@ def map_int_g(self, expr, name_hint=None):
         try:
             return self.expr_to_var[expr]
         except KeyError:
+            from pytential.utils import sort_arrays_together
+            densities, source_kernels = \
+                    *sort_arrays_together(expr.densities, expr.source_kernels)
```
Comment (inducer) [inline pytential/symbolic/compiler.py]: I'm honestly surprised this succeeds--what is it sorting by? [For the target derivatives](https://github.com/inducer/pytential/blob/b6e627ef815c740324e553615b2f4e21292b39ae/pytential/symbolic/compiler.py#L577), I ended up using `repr` as the sort key.

**Review by inducer — COMMENTED** [review]
Something I stumbled on (don't have time to finish the review tonight).

File: pytential/utils.py [hunk 18]
```diff
@@ -61,4 +61,8 @@ def flatten_to_numpy(actx, ary):
     from pytools.obj_array import obj_array_vectorize
     return obj_array_vectorize(actx.to_numpy, result)
 
+
+def sort_arrays_together(*arys, key=str):
+    return zip(*sorted([x for x in zip(*arys)], key=key))
```
Comment (isuruf) [inline pytential/utils.py:66]: @inducer, I'm sorting them using `str`. I can change that to `repr`.

Comment (inducer) [reply pytential/utils.py:66]: Ah. I had missed the default arg. IMO that default arg is easy to overlook. Put that into the calling code.

**Comment by inducer** [comment]
Merged the examples run, and it promptly died (i.e. it did its job :). Could you take a look?

File: pytential/qbx/direct.py [hunk 19]
```diff
@@ -115,6 +118,7 @@ def __call__(self, queue, targets, sources, centers, strengths, expansion_radii,
         for i, dens in enumerate(strengths):
             kwargs[f"strength_{i}"] = dens
 
+        print(knl)
```
Comment (inducer) [inline pytential/qbx/direct.py:121]:
```suggestion
```

Comment (isuruf) [reply pytential/qbx/direct.py]: Thanks

File: pytential/symbolic/primitives.py [hunk 20]
```diff
@@ -1664,6 +1665,31 @@ class _unspecified:  # noqa: N801
     pass
 
 
+def int_g_vec(kernel, density, qbx_forced_limit, source=None, target=None,
+        kernel_arguments=None, **kwargs):
+    """
+    Creates a vector of IntGs from one kernel with source and target derivatives
+    and maps a vector of densities into a vector of IntGs.
```
Comment (inducer) [inline pytential/symbolic/primitives.py:1672]: Explain a bit more about the history and why it's necessary.

File: pytential/symbolic/primitives.py [hunk 21]
```diff
@@ -1425,35 +1425,31 @@ class IntG(Expression):
...
         """*target_derivatives* and later arguments should be considered
         keyword-only.
 
-        :arg kernel: an instance of :class:`sumpy.kernel.Kernel`.
+        :arg source_kernels: a tuple of instances of :class:`sumpy.kernel.Kernel`
+            with only source derivatives attached. k-th elements represents the
+            k-th source derivative operator above.
+        :arg target_kernel: an instance of :class:`sumpy.kernel.Kernel` with only
+            target dervatives attached. This represents the target derivative
+            operator :math:`T` above.
```
Comment (inducer) [inline pytential/symbolic/primitives.py:1450]: Add a note that this interface is bad and will change.

File: pytential/symbolic/primitives.py [hunk 22]
```diff
@@ -1497,11 +1493,13 @@ def __init__(self, kernel, density,
...
-                for karg in (
-                    kernel.get_args()
-                    + kernel.get_source_args())}
+        source_kernels = tuple(source_kernels)
+        densities = tuple(densities)
+        kernel_arg_names = set()
+
+        for kernel in source_kernels + (target_kernel,):
+            for karg in (kernel.get_args() + kernel.get_source_args()):
+                kernel_arg_names.add(karg.loopy_arg.name)
```
Comment (inducer) [inline pytential/symbolic/primitives.py:1502]: Could you add a check that all the source and target kernels have the same base kernel? (And only the "right" kind of operator on each?)

File: pytential/symbolic/primitives.py (hunk 21 above)
Comment (inducer) [inline pytential/symbolic/primitives.py:1450]: Add a note that the base kernels of all supplied kernels should be the same.

**Review by inducer — COMMENTED** [review]
Thanks for working on this! A few (hopefully) easy things to resolve, after that it's ready to go in from my end.

**Comment by inducer** [comment]
> "Update pytential/symbolic/compiler.py"

Not liking this much as a commit message, generally. (OK this time, next time please type a short summary)

**Comment by inducer** [comment]
I've been trying to gain an understanding of the examples failures in #57, but no luck. It also seems that this branch produces them a lot more consistently than master somehow. @isuruf Do you have any idea what might be happening?

**Comment by inducer** [comment]
Died again. https://github.com/inducer/pytential/pull/38/checks?check_run_id=1912418396

I'll retry, but I haven't seen this succeed on this branch AFAIK.

File: pytential/symbolic/primitives.py [hunk 23]
```diff
@@ -1664,6 +1674,39 @@ class _unspecified:  # noqa: N801
...
+        kernel_arguments=None, **kwargs):
+    """
+    Creates a vector of :class:`IntG` objects from one kernel with source and
+    target derivatives and maps a vector of densities into a vector of
+    :class:`IntG` objects.
+
+    Historically :class:`IntG` objects supported only one source kernel and
+    allowed multiple densities to get a vector of objects as a convenience
+    function. Now that :class:`IntG` objects supports multiple source kernels
+    with one density associated to each source kernel, previous interface
```
Comment (inducer) [inline pytential/symbolic/primitives.py:1687]:
```suggestion
    with one density associated to each source kernel, the previous interface
```

File: pytential/symbolic/primitives.py [hunk 24]
```diff
@@ -1664,6 +1674,39 @@ class _unspecified:  # noqa: N801
...
+    would lead to ambiguity. This function is intended to preserve the
+    interface of the constructor of :class:`IntG` for easy transition.
```
Comment (inducer) [inline pytential/symbolic/primitives.py:1689]:
```suggestion
    "vectorizing" behavior of of the constructor of :class:`IntG`
    for use cases where that is preferred.
```

File: pytential/symbolic/compiler.py [hunk 25]
```diff
@@ -137,21 +137,27 @@ class ComputePotentialInstruction(Instruction):
...
-        layer potentials removed.
+        a list of :class:`sumpy.kernel.Kernel` instances with only source
+        derivatives and no target derivatives. See
+        :class:`pytential.symbolic.primitives.IntG` docstring for details.
+
+    .. attribute:: densities
+
+        a list of densities with the same number of entries as
+        :attr:`source_kernels`. See :class:`pytential.symbolic.primitives.IntG`
+        docstring for details.
```
Comment (inducer) [inline pytential/symbolic/compiler.py:159]:
```suggestion
        :attr:`source_kernels`. See the :class:`pytential.symbolic.primitives.IntG`
        docstring for details.
```

**Review by inducer — APPROVED** [review]
Thanks for working on this!

**Comment by kaushikcfd** [comment]
Probably broke pytential?
>  AttributeError: 'QBXSumpyExpansionWranglerCodeContainer' object has no attribute 'out_kernels'

https://github.com/inducer/loopy/runs/1974526896?check_suite_focus=true

**Comment by inducer** [comment]
That was temporary, and caused by https://github.com/inducer/sumpy/pull/23, really. https://github.com/inducer/sumpy/pull/23 and this need to merge together, however there was a  brief window (about an hour) where https://github.com/inducer/sumpy/pull/23 was merged and this was not. Just rerun, you should be OK. Sorry that you got caught up in the fallout from this.
